# Generated by Django 3.2.12 on 2022-04-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('vegetarian', models.TextField(max_length=110)),
                ('non_vegetarian', models.TextField(max_length=110)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
