# Generated by Django 3.2.11 on 2022-03-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restrrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, unique=True)),
                ('slug', models.SlugField(max_length=290, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(blank=True, upload_to='items1')),
                ('avialable', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restrrapp.category')),
            ],
            options={
                'verbose_name': 'items1',
                'verbose_name_plural': 'items1',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
