# Generated by Django 3.2.11 on 2022-03-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restrrapp', '0002_auto_20220329_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items1',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Items1',
        ),
    ]
